// Every flag the CLI knows. History reads recorded words with the same table, so `--ref e5` parses the
// way the CLI parsed it.
export const cliOptions = {
  profile: { type: "string" },
  session: { type: "string" },
  json: { type: "boolean", default: false },
  "timeout-ms": { type: "string" },
  wait: { type: "string" },
  all: { type: "boolean", default: false },
  inline: { type: "boolean", default: false },
  full: { type: "boolean", default: false },
  ref: { type: "string" },
  "main-world": { type: "boolean", default: false },
  url: { type: "string" },
  type: { type: "string" },
  status: { type: "string" },
  body: { type: "boolean", default: false },
  until: { type: "string" },
  domain: { type: "string" },
  level: { type: "string" },
  follow: { type: "boolean", default: false },
  mode: { type: "string" },
  isolated: { type: "boolean", default: false },
  from: { type: "string" },
  selector: { type: "string" },
  text: { type: "string" },
  title: { type: "string" },
  load: { type: "string" },
  gone: { type: "boolean", default: false },
  events: { type: "string" },
  count: { type: "string" },
  frame: { type: "string" },
  at: { type: "string" },
  handoff: { type: "boolean", default: false },
  role: { type: "string" },
  name: { type: "string" },
  exact: { type: "boolean", default: false },
  nth: { type: "string" },
  label: { type: "string" },
  out: { type: "string" },
  format: { type: "string" },
  bail: { type: "boolean", default: false },
} as const;
